# This file describes the post-processing steps for transform
# The examples below multiplies the volume column by its specified value
SGD.IDX-SGD:
  post:
    volume-adjust:
      action: multiply
      column: volume
      value: 1200
CHI.IDX-USD:
  post:
    volume-adjust:
      action: multiply
      column: volume
      value: 34484
