America/New_York:                 # The MT4 Server switches between GMT+2/GMT+3 based on DST change of this timezone
  offset_to_shift_map:            # Defines a map to shift based on offset minutes
    -240: 10800000                # UTC-4 (US DST) -> GMT+3 shift
    -300: 7200000                 # UTC-5 (US Standard) -> GMT+2 shift
  symbols:                        # Basically you add any symbol you are using here.
  # --- Commodities (Precious Metals & Energy) ---
  - BRENT.CMD-USD                 # OK
  - COPPER.CMD-USD                # OK
  - DIESEL.CMD-USD                # OK
  - GAS.CMD-USD                   # OK
  - LIGHT.CMD-USD                 # OK
  - XAG-USD                       # OK
  - XAU-USD                       # OK
  - XPD.CMD-USD                   # OK
  - XPT.CMD-USD                   # OK

  # --- Soft Commodities ---
  - COTTON.CMD-USX
  - OJUICE.CMD-USX
  - SOYBEAN.CMD-USX

  # --- Currencies ---
  - DOLLAR.IDX-USD                # OK
  - USD-JPY                       # OK
  - EUR-USD                       # OK
  - GBP-USD                       # OK
  - USD-CHF                       # OK
  - AUD-USD                       # OK
  - USD-CAD                       # OK
  - NZD-USD                       # W1 is unusable
  - EUR-NZD                       # OK

  # --- Indices (US) ---
  - USA30.IDX-USD                 # OK
  - USA500.IDX-USD                # OK
  - USATECH.IDX-USD               # OK
  - USSC2000.IDX-USD              # OK
  - VOL.IDX-USD                   # OK

  # --- Indices (Non-US) ---
  - AUS.IDX-AUD                   # OK - Australian Index (ASX) (checked from 2020-03 to now)
  - CHE.IDX-CHF                   # OK - Swiss Index (SMI)
  - DEU.IDX-EUR                   # OK - German Index (DAX)
  - ESP.IDX-EUR                   # OK - Spanish Index (IBEX 35)
  - EUS.IDX-EUR                   # OK - Euro Index (Euro Stoxx)
  - FRA.IDX-EUR                   # OK - French Index (CAC 40)
  - ITA.IDX-EUR                   # OK - Italian Index (FTSE MIB)
  - GBR.IDX-GBP                   # OK - UK Index (FTSE 100)
  - HKG.IDX-HKD                   # OK - Hong Kong Index (HSI) (checked from 2023-06 to now)
  - JPN.IDX-JPY                   # OK - Japanese Index (Nikkei)
  - NLD.IDX-EUR                   # OK - Netherlands Index (AEX)
  - PLN.IDX-PLN                   # OK - Polish Index (WIG20)
  - SGD.IDX-SGD                   # NOK - Singapore Index (STI) (EDGE CASE ON H4)

  # --- Bonds/Rates ---
  - BUND.TR-EUR                   # OK (only week-start off by 0.01 or 0.02)
  - USTBOND.TR-USD                # OK (only week-start off by 0.01 or 0.02)