DEU.IDX-EUR:
  timeframes:
    4h:                     
      rule: "4H"
      label: "left"
      closed: "left"
      source: "1h"
      origin: "01:00"
NLD.IDX-EUR:
  timeframes:
    4h:                     
      rule: "4H"
      label: "left"
      closed: "left"
      source: "1h"
      origin: "09:00" 
