# HKG.IDX-HKD (HSI). The Aussie index has 3 trading sessions (for futures and derivatives). 
# 
# - Morning Session: 9:15 AM - 12:00 PM (HKT)
# - Afternoon Session: 1:00 PM - 4:30 PM (HKT)
# - After-Hours Trading (AHT): 5:15 PM - 3:00 AM next day (HKT)
# - Lunch Break: 12:00 PM - 1:00 PM (1 hour)
#
# >>This one is OK from 2023-03-01 to now<< (not further checked atm)
#
# MT4 may have different candle alignment policy before that date. If so: another update is incoming.
#
# Please note that the ORIGIN field is set to the candle alignment as if it were winter in Europe.
# 
HKG.IDX-HKD:
  timezone: Asia/Hong_Kong
  skip_timeframes: []
  sessions:
    morning:
      ranges:
        open:
          from: "09:15"
          to: "12:00"
      timeframes:
        15m:
          rule: "15T"
          label: "left"
          closed: "left"
          source: "5m"
          origin: "03:15"
        30m:
          rule: "30T"
          label: "left"
          closed: "left"
          source: "15m"
          origin: "03:15"
        1h:
          rule: "1H"
          label: "left"
          closed: "left"
          source: "30m"
          origin: "03:15"
        4h:
          rule: "4H"
          label: "left"
          closed: "left"
          source: "1h"
          origin: "03:15"
        8h:
          rule: "8H"
          label: "left"
          closed: "left"
          source: "1h"
          origin: "03:15"
    afternoon:
      ranges:
        reopen:
          from: "13:00"
          to: "16:30"
      timeframes:
        15m:
          rule: "15T"
          label: "left"
          closed: "left"
          source: "5m"
          origin: "07:00"
        30m:
          rule: "30T"
          label: "left"
          closed: "left"
          source: "15m"
          origin: "07:00"
        1h:
          rule: "1H"
          label: "left"
          closed: "left"
          source: "30m"
          origin: "07:00"
        4h:
          rule: "4H"
          label: "left"
          closed: "left"
          source: "1h"
          origin: "07:00"
        8h:
          rule: "8H"
          label: "left"
          closed: "left"
          source: "1h"
          origin: "07:00"
    after-hours:
      ranges:
        evening:
          from: "17:15"
          to: "23:59"
        night:
          from: "00:00"
          to: "03:00"
      timeframes:
        15m:
          rule: "15T"
          label: "left"
          closed: "left"
          source: "5m"
          origin: "11:15"
        30m:
          rule: "30T"
          label: "left"
          closed: "left"
          source: "15m"
          origin: "11:15"
        1h:
          rule: "1H"
          label: "left"
          closed: "left"
          source: "30m"
          origin: "11:15"
        4h:
          rule: "4H"
          label: "left"
          closed: "left"
          source: "1h"
          origin: "11:15"
        8h:
          rule: "8H"
          label: "left"
          closed: "left"
          source: "1h"
          origin: "11:15"
    # to catch any "OLD ERA" behavior of Dukascopy (prevent out_of_market errors)
    catch-old:
      ranges: 
        day:
          from: "00:00"
          to: "23:59"
      timeframes:                    
        15m:                     
          rule: "15T"
          label: "left"
          closed: "left"
          source: "5m"
          origin: "00:00"
        30m:                     
          rule: "30T"
          label: "left"
          closed: "left"
          source: "15m"
          origin: "00:00" 
        1h:                     
          rule: "1H"
          label: "left"
          closed: "left"
          source: "30m"
          origin: "00:00"
        4h:                     
          rule: "4H"
          label: "left"
          closed: "left"
          source: "1h"
          origin: "00:00"
        8h:                     
          rule: "8H"
          label: "left"
          closed: "left"
          source: "1h"
          origin: "00:00"
        1d:                     
          rule: "1D"
          label: "left"
          closed: "left"
          source: "4h"
          origin: "00:00"  