USA30.IDX-USD:          # 2025-12-14: OK
  timeframes:
    4h:                     
      rule: "4H"
      label: "left"
      closed: "left"
      source: "1h"
      origin: "01:00"
USA500.IDX-USD:         # 2025-12-14: OK
  timeframes:
    4h:                     
      rule: "4H"
      label: "left"
      closed: "left"
      source: "1h"
      origin: "01:00"
USATECH.IDX-USD:        # 2025-12-14: OK
  timeframes:
    4h:                     
      rule: "4H"
      label: "left"
      closed: "left"
      source: "1h"
      origin: "01:00"
USSC2000.IDX-USD:       # 2025-12-14: OK
  timeframes:
    4h:                     
      rule: "4H"
      label: "left"
      closed: "left"
      source: "1h"
      origin: "01:00"
DOLLAR.IDX-USD:         # 2025-12-14: OK
  timeframes:
    4h:                     
      rule: "4H"
      label: "left"
      closed: "left"
      source: "1h"
      origin: "03:00"
VOL.IDX-USD:            # 2025-12-14: OK
  timeframes:
    4h:                     
      rule: "4H"
      label: "left"
      closed: "left"
      source: "1h"
      origin: "01:00"