America/New_York:                 # The MT4 Server switches between GMT+2/GMT+3 based on DST change of this timezone
  offset_to_shift_map:            # Defines a map to shift based on offset minutes
    -240: 10800000                # UTC-4 (US DST) -> GMT+3 shift
    -300: 7200000                 # UTC-5 (US Standard) -> GMT+2 shift
  symbols:                        # Basically you add any symbol you are using here.
  # --- Commodities (Precious Metals & Energy) ---
  - BRENT.CMD-USD                 # OK
  - COPPER.CMD-USD                # OK
  - DIESEL.CMD-USD                # OK
  - GAS.CMD-USD                   # OK
  - LIGHT.CMD-USD                 # OK
  - XAG-USD                       # OK
  - XAU-USD                       # OK
  - XPD.CMD-USD                   # OK
  - XPT.CMD-USD                   # OK

  # --- Soft Commodities ---
  - COTTON.CMD-USX                # OK
  - OJUICE.CMD-USX                # OK
  - SOYBEAN.CMD-USX               # NOK (1Y timeframe throws a OUT_OF_MARKET? rest is OK.)

  # --- Currencies ---
  - DOLLAR.IDX-USD                # OK - US Dollar Index
  - AUD-CAD                       # Australian Dollar vs Canadian Dollar
  - AUD-CHF                       # Australian Dollar vs Swiss Franc
  - AUD-JPY                       # Australian Dollar vs Yen
  - AUD-NZD                       # Australian Dollar vs New Zealand Dollar
  - AUD-SGD                       # Australian Dollar vs Singapore Dollar
  - AUD-USD                       # OK - Australian Dollar vs US Dollar
  - CAD-CHF                       # Canadian Dollar vs Swiss Franc
  - CAD-HKD                       # Canadian Dollar vs Hong Kong Dollar
  - CAD-JPY                       # Canadian Dollar vs Yen
  - CHF-JPY                       # Swiss Franc vs Yen
  - CHF-PLN                       # Swiss Franc vs Zloty
  - CHF-SGD                       # Swiss Franc vs Singapore Dollar
  - EUR-AUD                       # Euro vs Australian Dollar
  - EUR-CAD                       # Euro vs Canadian Dollar
  - EUR-CHF                       # Euro vs Swiss Franc
  - EUR-CZK                       # Euro vs Czech Koruna
  - EUR-DKK                       # Euro vs Danish Krone
  - EUR-GBP                       # Euro vs Pound Sterling
  - EUR-HKD                       # Euro vs Hong Kong Dollar
  - EUR-HUF                       # Euro vs Hungarian Forint
  - EUR-JPY                       # Euro vs Yen
  - EUR-MXN                       # Euro vs Mexican Peso
  - EUR-NOK                       # Euro vs Norwegian Krone
  - EUR-NZD                       # OK - Euro vs New Zealand Dollar
  - EUR-PLN                       # Euro vs Zloty
  - EUR-SEK                       # Euro vs Swedish Krona
  - EUR-SGD                       # Euro vs Singapore Dollar
  - EUR-TRY                       # Euro vs Turkish Lira
  - EUR-USD                       # OK - Euro vs US Dollar
  - EUR-ZAR                       # Euro vs Rand
  - GBP-AUD                       # Pound Sterling vs Australian Dollar
  - GBP-CAD                       # Pound Sterling vs Canadian Dollar
  - GBP-CHF                       # Pound Sterling vs Swiss Franc
  - GBP-JPY                       # Pound Sterling vs Yen
  - GBP-NZD                       # Pound Sterling vs New Zealand Dollar
  - GBP-USD                       # OK - Pound Sterling vs US Dollar
  - HKD-JPY                       # Hong Kong Dollar vs Yen
  - MXN-JPY                       # Mexican Peso vs Yen
  - NZD-CAD                       # New Zealand Dollar vs Canadian Dollar
  - NZD-CHF                       # New Zealand Dollar vs Swiss Franc
  - NZD-JPY                       # New Zealand Dollar vs Yen
  - NZD-SGD                       # New Zealand Dollar vs Singapore Dollar
  - NZD-USD                       # NOK - New Zealand Dollar vs US Dollar (W1 unusable)
  - SGD-JPY                       # Singapore Dollar vs Yen
  - TRY-JPY                       # Turkish Lira vs Yen
  - USD-CAD                       # OK - US Dollar vs Canadian Dollar
  - USD-CHF                       # OK - US Dollar vs Swiss Franc
  - USD-CNH                       # US Dollar vs Chinese Yuan
  - USD-CZK                       # US Dollar vs Czech Koruna
  - USD-DKK                       # US Dollar vs Danish Krone
  - USD-HKD                       # US Dollar vs Hong Kong Dollar
  - USD-HUF                       # US Dollar vs Hungarian Forint
  - USD-ILS                       # US Dollar vs Israeli Shekel
  - USD-JPY                       # OK - US Dollar vs Yen
  - USD-MXN                       # US Dollar vs Mexican Peso
  - USD-NOK                       # US Dollar vs Norwegian Krone
  - USD-PLN                       # US Dollar vs Zloty
  - USD-RON                       # US Dollar vs Romanian Leu
  - USD-SEK                       # US Dollar vs Swedish Krona
  - USD-SGD                       # US Dollar vs Singapore Dollar
  - USD-THB                       # US Dollar vs Thai Baht
  - USD-TRY                       # US Dollar vs Turkish Lira
  - USD-ZAR                       # US Dollar vs Rand
  - ZAR-JPY                       # Rand vs Yen

  # --- Crypto (Bitcoin) ---
  - BTC-USD                       # OK - Bitcoin vs US Dollar
  - BTC-CHF                       # OK - Bitcoin vs Swiss Franc
  - BTC-EUR                       # OK - Bitcoin vs Euro
  - BTC-GBP                       # OK - Bitcoin vs Pound Sterling

  # --- Indices (US) ---
  - USA30.IDX-USD                 # OK
  - USA500.IDX-USD                # OK
  - USATECH.IDX-USD               # OK
  - USSC2000.IDX-USD              # OK
  - VOL.IDX-USD                   # OK

  # --- Indices (Non-US) ---
  - AUS.IDX-AUD                   # OK - Australian Index (ASX) (checked from 2020-03 to now)
  - CHI.IDX-USD                   # OK - Chinese Index (A50)
  - CHE.IDX-CHF                   # OK - Swiss Index (SMI)
  - DEU.IDX-EUR                   # OK - German Index (DAX)
  - ESP.IDX-EUR                   # OK - Spanish Index (IBEX 35)
  - EUS.IDX-EUR                   # OK - Euro Index (Euro Stoxx)
  - FRA.IDX-EUR                   # OK - French Index (CAC 40)
  - ITA.IDX-EUR                   # OK - Italian Index (FTSE MIB)
  - GBR.IDX-GBP                   # OK - UK Index (FTSE 100)
  - HKG.IDX-HKD                   # OK - Hong Kong Index (HSI) (checked from 2023-06 to now)
  - JPN.IDX-JPY                   # OK - Japanese Index (Nikkei)
  - NLD.IDX-EUR                   # OK - Netherlands Index (AEX)
  - PLN.IDX-PLN                   # OK - Polish Index (WIG20)
  - SGD.IDX-SGD                   # NOK - Singapore Index (STI) (EDGE CASE ON H4)
  - SOA.IDX-ZAR                   # OK - South Africa Index (JSE/ALSI)

  # --- Bonds/Rates ---
  - BUND.TR-EUR                   # OK
  - USTBOND.TR-USD                # OK